### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by DuncanMarten** [MarynaPR/24-chains#52]
Render favorite courses
render reviewed courses and played courses
add user firstname and lastname to top of page

**Comment by njderenne** [comment]
reviewed courses are now rendered.
Need to update/fix the favorited route to link to the favorited course list on profile

**Comment by njderenne** [comment]
* add user firstname and lastname to the top of the page
* add played courses with the reviewed courses
* create a separate  rated courses page that displays a list of all reviews done by the user
* remove gray box from the buttons
* populate ABOUT USER section
* update styling

**Comment by njderenne** [comment]
Only need to populate ABOUT USER section
