### ISSUE TITLE
Update Homepage Front end

### ISSUE THREAD

**Issue by njderenne** [MarynaPR/24-chains#70]
* List of reviews and activities starting with most recent post
*  Update Search bar text
* Add functionality to search bar for both course city and course name

##Secondary
* Update Logout Font (main.handlebars)
* Update 24 chains font size (main.handlebars)
* Capitalize C in chains (main.handlebars)
* Resize the search bar height

**Comment by frostyausty** [comment]
Need to update the handlebars to pull city and state from course model, where needed.
