### ISSUE TITLE
Back end Individual Course Listing

### ISSUE THREAD

**Issue by njderenne** [MarynaPR/24-chains#73]
* add functionality to the favorite button
* add functionality to the submit review button
* add functionality to the rating disc buttons (i.e. one disc = 1/5)
## Secondary
* fill discs on click event for rating
* add functionality tot he saved course button

**Comment by DuncanMarten** [comment]
favorite button works
Submit review button works

**Comment by DuncanMarten** [comment]
rating can be pulled
